/*
Copyright (C) 2025 QuantumNous

Local documentation page — bilingual, dark-mode aware, multi-page.
Routes: /docs/:slug+ (e.g. /docs/getting-started, /docs/guides/streaming)
*/

import React, { useEffect, useMemo, useState, useCallback, useRef } from 'react';
// Generated By AI End (Cursor)
import { useParams, useNavigate, Navigate, useLocation } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { docTree, getDoc, allSlugsFlat } from './content';
import { useIsMobile } from '../../hooks/common/useIsMobile';

// ---------- Code block with copy ----------
const CodeBlock = ({ code, lang, copyLabel, copiedLabel }) => {
  const [copied, setCopied] = useState(false);
  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }, [code]);
  return (
    <div className='docs-code-block'>
      <div className='docs-code-header'>
        <span className='docs-code-lang'>{lang}</span>
        <button className='docs-code-copy' onClick={handleCopy}>
          {copied ? copiedLabel : copyLabel}
        </button>
      </div>
      <pre><code>{code}</code></pre>
    </div>
  );
};

// ---------- Tabs (multi-language code) ----------
const CodeTabs = ({ tabs, copyLabel, copiedLabel }) => {
  const [active, setActive] = useState(0);
  const t = tabs[active];
  return (
    <div>
      <div className='docs-tabs'>
        {tabs.map((tab, i) => (
          <button
            key={tab.label}
            className={`docs-tab ${active === i ? 'active' : ''}`}
            onClick={() => setActive(i)}
          >
            {tab.label}
          </button>
        ))}
      </div>
      <CodeBlock code={t.code} lang={t.lang} copyLabel={copyLabel} copiedLabel={copiedLabel} />
    </div>
  );
};

// ---------- Block renderer ----------
const Block = ({ block, ui }) => {
  switch (block.type) {
    case 'h2':
      return (
        <h2 className='docs-h2' id={slugifyHeading(block.text)}>
          <span className='docs-h2-bar' />
          {block.text}
        </h2>
      );
    case 'h3':
      return <h3 className='docs-h3'>{block.text}</h3>;
    case 'p':
      return <p className='docs-p'>{block.text}</p>;
    case 'list':
      return (
        <ul className='docs-list'>
          {block.items.map((it, i) => (
            <li key={i}>{it}</li>
          ))}
        </ul>
      );
    case 'table':
      return (
        <div className='docs-table-wrapper'>
          <table className='docs-table'>
            <thead>
              <tr>
                {block.headers.map((h) => (
                  <th key={h}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {block.rows.map((row, i) => (
                <tr key={i}>
                  {row.map((cell, j) => (
                    <td key={j}>{cell}</td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      );
    case 'code':
      return <CodeBlock code={block.code} lang={block.lang} copyLabel={ui.copy} copiedLabel={ui.copied} />;
    case 'tabs':
      return <CodeTabs tabs={block.tabs} copyLabel={ui.copy} copiedLabel={ui.copied} />;
    case 'callout':
      return (
        <div className={`docs-callout docs-callout-${block.kind || 'info'}`}>
          <div className='docs-callout-icon'>
            {block.kind === 'warn' ? '!' : block.kind === 'tip' ? '★' : 'i'}
          </div>
          <div className='docs-callout-text'>{block.text}</div>
        </div>
      );
    case 'cards':
      return (
        <div className='docs-card-grid'>
          {block.items.map((c, i) => (
            <div key={i} className='docs-content-card'>
              <div className='docs-content-card-header'>
                <h4>{c.title}</h4>
                {c.badge && <span className='docs-content-card-badge'>{c.badge}</span>}
              </div>
              <p>{c.desc}</p>
            </div>
          ))}
        </div>
      );
    case 'metrics':
      return (
        <div className='docs-metrics-grid'>
          {block.items.map((m, i) => (
            <div key={i} className='docs-metric-card'>
              <div className='docs-metric-label'>{m.label}</div>
              <div className='docs-metric-value'>{m.value}</div>
              <div className='docs-metric-sub'>{m.sub}</div>
            </div>
          ))}
        </div>
      );
    default:
      return null;
  }
};

const slugifyHeading = (text) =>
  text
    .toString()
    .trim()
    .replace(/\s+/g, '-')
    .replace(/[^\w\u4e00-\u9fa5-]/g, '');

// ---------- Sidebar ----------
const Sidebar = ({ tree, currentSlug, onNavigate, lang }) => {
  // Auto-expand the group containing the current slug
  const initiallyExpanded = useMemo(() => {
    const expanded = {};
    tree.forEach((node, i) => {
      if (node.type === 'group') {
        if (node.items.some((it) => it.slug === currentSlug)) {
          expanded[i] = true;
        } else {
          expanded[i] = true; // default all expanded for discoverability
        }
      }
    });
    return expanded;
  }, [tree, currentSlug]);

  const [expanded, setExpanded] = useState(initiallyExpanded);

  const toggleGroup = (i) =>
    setExpanded((prev) => ({ ...prev, [i]: !prev[i] }));

  const renderItem = (slug, isChild) => {
    const doc = getDoc(slug, lang);
    if (!doc) return null;
    const isActive = slug === currentSlug;
    return (
      <a
        key={slug}
        href={`/docs/${slug}`}
        onClick={(e) => {
          e.preventDefault();
          onNavigate(slug);
        }}
        className={`docs-sidebar-link ${isActive ? 'active' : ''} ${isChild ? 'child' : ''}`}
      >
        {doc.title}
      </a>
    );
  };

  return (
    <aside className='docs-sidebar'>
      <div className='docs-sidebar-header'>
        <div className='docs-sidebar-title'>Documentation</div>
        <div className='docs-sidebar-version'>v1.0 · STABLE</div>
      </div>
      <nav className='docs-sidebar-nav'>
        {tree.map((node, i) => {
          if (node.type === 'item') {
            return renderItem(node.slug, false);
          }
          // group
          const isOpen = expanded[i] !== false;
          return (
            <div key={i} className='docs-sidebar-group'>
              <button
                className='docs-sidebar-group-header'
                onClick={() => toggleGroup(i)}
              >
                <span>{node.label}</span>
                <svg
                  width='14'
                  height='14'
                  viewBox='0 0 24 24'
                  fill='none'
                  stroke='currentColor'
                  strokeWidth='2'
                  strokeLinecap='round'
                  strokeLinejoin='round'
                  style={{
                    transition: 'transform 200ms ease',
                    transform: isOpen ? 'rotate(180deg)' : 'rotate(0deg)',
                  }}
                >
                  <polyline points='6 9 12 15 18 9' />
                </svg>
              </button>
              {isOpen && (
                <div className='docs-sidebar-group-items'>
                  {node.items.map((child) => renderItem(child.slug, true))}
                </div>
              )}
            </div>
          );
        })}
      </nav>
    </aside>
  );
};

// ---------- Main page ----------
const Docs = () => {
  const { i18n } = useTranslation();
  const params = useParams();
  const navigate = useNavigate();
  const location = useLocation();
  const isMobile = useIsMobile();
  const [mobileNavOpen, setMobileNavOpen] = useState(false);
  const lang = i18n.language && i18n.language.startsWith('en') ? 'en' : 'zh';

  const ui = useMemo(
    () => ({
      onThisPage: lang === 'en' ? 'On This Page' : '本页目录',
      copy: lang === 'en' ? 'Copy' : '复制',
      copied: lang === 'en' ? 'Copied' : '已复制',
      prev: lang === 'en' ? 'Previous' : '上一篇',
      next: lang === 'en' ? 'Next' : '下一篇',
      notFound: lang === 'en' ? 'Page not found' : '页面不存在',
    }),
    [lang],
  );

  // Resolve current slug from URL — supports nested like guides/streaming
  const currentSlug = useMemo(() => {
    // Strip leading /docs/
    const path = location.pathname.replace(/^\/docs\/?/, '').replace(/\/$/, '');
    return path || 'getting-started';
  }, [location.pathname]);

  // Redirect bare /docs to /docs/getting-started
  if (location.pathname === '/docs' || location.pathname === '/docs/') {
    return <Navigate to='/docs/getting-started' replace />;
  }

  // 动态获取当前站点 origin，用于替换文档中的 your-domain 占位符
  const siteOrigin = window.location.origin;
  const doc = getDoc(currentSlug, lang, siteOrigin);
  // Generated By AI End (Cursor)
  const tree = useMemo(() => docTree(lang), [lang]);

  // TOC: collect h2 headings from current doc
  const toc = useMemo(() => {
    if (!doc) return [];
    return doc.sections
      .filter((s) => s.type === 'h2')
      .map((s) => ({ id: slugifyHeading(s.text), text: s.text }));
  }, [doc]);

  const [activeHeading, setActiveHeading] = useState('');
  const mainRef = useRef(null);

  useEffect(() => {
    if (!toc.length) return;
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) setActiveHeading(e.target.id);
        });
      },
      { root: mainRef.current, rootMargin: '-30% 0px -60% 0px' },
    );
    toc.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, [toc]);

  // Scroll to top on slug change — scroll the main content column, not the window
  useEffect(() => {
    if (mainRef.current) {
      mainRef.current.scrollTo({ top: 0, behavior: 'instant' });
    }
  }, [currentSlug]);
  // Generated By AI End (Cursor)

  // Prev/next nav
  const { prev, next } = useMemo(() => {
    const idx = allSlugsFlat.indexOf(currentSlug);
    return {
      prev: idx > 0 ? allSlugsFlat[idx - 1] : null,
      next: idx >= 0 && idx < allSlugsFlat.length - 1 ? allSlugsFlat[idx + 1] : null,
    };
  }, [currentSlug]);

  const goToSlug = useCallback(
    (slug) => {
      navigate(`/docs/${slug}`);
      setMobileNavOpen(false);
    },
    [navigate],
  );

  const renderMobileSidebarLayer = () => {
    if (!isMobile) return null;
    return (
      <>
        <button
          type='button'
          className='docs-mobile-nav-toggle'
          aria-label={lang === 'en' ? 'Open documentation menu' : '打开文档目录'}
          onClick={() => setMobileNavOpen(true)}
        >
          <svg width='18' height='18' viewBox='0 0 24 24' fill='none' stroke='currentColor' strokeWidth='2.2' strokeLinecap='round' strokeLinejoin='round'>
            <line x1='3' y1='6' x2='21' y2='6' />
            <line x1='3' y1='12' x2='21' y2='12' />
            <line x1='3' y1='18' x2='15' y2='18' />
          </svg>
          <span>{lang === 'en' ? 'Docs menu' : '文档目录'}</span>
        </button>
        {mobileNavOpen && (
          <>
            <div className='docs-mobile-backdrop' onClick={() => setMobileNavOpen(false)} />
            <div className='docs-mobile-drawer'>
              <Sidebar tree={tree} currentSlug={currentSlug} onNavigate={goToSlug} lang={lang} />
            </div>
          </>
        )}
      </>
    );
  };

  if (!doc) {
    return (
      <div className='docs-page'>
        <Sidebar tree={tree} currentSlug={currentSlug} onNavigate={goToSlug} lang={lang} />
        {renderMobileSidebarLayer()}
        <main className='docs-main'>
          <h1 className='docs-h1'>{ui.notFound}</h1>
          <p className='docs-intro'>404</p>
        </main>
      </div>
    );
  }

  return (
    <div className='docs-page'>
      <Sidebar tree={tree} currentSlug={currentSlug} onNavigate={goToSlug} lang={lang} />
      {renderMobileSidebarLayer()}
      {}
      <main className='docs-main' ref={mainRef}>
        <section className='docs-section'>
          {doc.badge && <div className='docs-badge'>{doc.badge}</div>}
          <h1 className='docs-h1'>{doc.title}</h1>
          <p className='docs-intro'>{doc.desc}</p>
        </section>

        <div className='docs-content'>
          {doc.sections.map((block, i) => (
            <Block key={i} block={block} ui={ui} />
          ))}
        </div>

        {/* Prev / Next */}
        <div className='docs-pagination'>
          {prev ? (
            <button className='docs-page-nav prev' onClick={() => goToSlug(prev)}>
              <span className='docs-page-nav-label'>← {ui.prev}</span>
              <span className='docs-page-nav-title'>{getDoc(prev, lang)?.title}</span>
            </button>
          ) : (
            <span />
          )}
          {next ? (
            <button className='docs-page-nav next' onClick={() => goToSlug(next)}>
              <span className='docs-page-nav-label'>{ui.next} →</span>
              <span className='docs-page-nav-title'>{getDoc(next, lang)?.title}</span>
            </button>
          ) : (
            <span />
          )}
        </div>
      </main>
      {}

      {toc.length > 0 && (
        <aside className='docs-toc'>
          <div className='docs-toc-title'>{ui.onThisPage}</div>
          <nav className='docs-toc-nav'>
            {toc.map(({ id, text }) => (
              <a
                key={id}
                href={`#${id}`}
                onClick={(e) => {
                  e.preventDefault();
                  const el = document.getElementById(id);
                  if (el && mainRef.current) {
                    const offset = el.offsetTop - mainRef.current.offsetTop - 24;
                    mainRef.current.scrollTo({ top: offset, behavior: 'smooth' });
                  }
                }}
                className={`docs-toc-link ${activeHeading === id ? 'active' : ''}`}
              >
                {text}
              </a>
            ))}
          </nav>
        </aside>
      )}
    </div>
  );
};

export default Docs;
